/*
 * This file was generated by linkcmd_gnu.xdt from the ti.platforms.tiva package.
 */

__STACK_SIZE = 0x400;
__TI_STACK_SIZE = __STACK_SIZE;

INPUT(
    /home/satish/workspace_v9/esp8266_tm4c123/Debug/configPkg/package/cfg/app_pm4fg.om4fg
    /home/satish/workspace_v9/esp8266_tm4c123/src/sysbios/sysbios.am4fg
    /home/satish/ti/bios_6_76_02_02/packages/ti/catalog/arm/cortexm4/tiva/ce/lib/Boot.am4fg
    /home/satish/ti/bios_6_76_02_02/packages/gnu/targets/arm/rtsv7M/lib/gnu.targets.arm.rtsv7M.am4fg
    /home/satish/ti/bios_6_76_02_02/packages/gnu/targets/arm/rtsv7M/lib/boot.am4fg
    /home/satish/ti/bios_6_76_02_02/packages/gnu/targets/arm/rtsv7M/lib/syscalls.am4fg
    /home/satish/ti/ccs920/xdctools_3_60_01_27_core/packages/xdc/rov/runtime/lib/xdc.rov.runtime.am4fg
)

/*
 * symbolic aliases for static instance objects
 */
xdc_runtime_Startup__EXECFXN__C = 1;
xdc_runtime_Startup__RESETFXN__C = 1;
xdc_rov_runtime_Mon__checksum = 1;
xdc_rov_runtime_Mon__write = 1;


SECTIONS {

        .bootVecs (DSECT) : {*(.bootVecs)} 
    xdc.meta (COPY) : {KEEP(*(xdc.meta))}  AT> REGION_TEXT


    /*
     * Linker command file contributions from all loaded packages:
     */
    
/* Content from ti.sysbios.family.arm (ti/sysbios/family/arm/linkcmd.xdt): */

/* Content from ti.sysbios.family.arm.m3 (ti/sysbios/family/arm/m3/linkcmd.xdt): */
    _intvecs_base_address = 0;
    _vtable_base_address = 536870912;
ti_sysbios_family_arm_m3_Hwi_nvic = 0xe000e000;


    __TI_STACK_BASE = __stack;
}

ENTRY(_c_int00)

/* function aliases */
xdc_runtime_System_asprintf_va__E = xdc_runtime_System_asprintf_va__F;
xdc_runtime_System_snprintf_va__E = xdc_runtime_System_snprintf_va__F;
xdc_runtime_System_printf_va__E = xdc_runtime_System_printf_va__F;
xdc_runtime_System_aprintf_va__E = xdc_runtime_System_aprintf_va__F;
xdc_runtime_System_sprintf_va__E = xdc_runtime_System_sprintf_va__F;
